---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-mkcert
description: Install mkcert through ansible
tags:
  - ansible
  - ansible-role
  - mkcert
github:
  has_issues: true
  has_projects: false
  has_wiki: false
